### ISSUE TITLE
Logbook & images rendering optimizations

### ISSUE THREAD

**Issue by Grenadingue** [lumy/EternityII#40]
Logbook Optimization:

-  When calling the Stats.write_logbook() function we append to the logbookfile,
-  We should also reset the logbook inside the Stats instance so the ram get Free.
-  Create a main function inside Stats file where you can give him a folder path and it render everything inside (graph).

Rendering Optimization:

- Create a main function inside eternity.py so you can call the file with an path so render everything inside (image)

Finally find a place to add a function call for rendering (maybe in the main.py with an  option maybe in a file render.py to keep clear).

**Comment by lumy** [comment]
After few test it's seems that we can't add easily two logbook together (not without forking deap).
So what i propose is the register the population in another binary file instead of the logbook.
(concretly it had one variable to manage, and one file to save/read when needing (drawing images)).

Is that solution look suitable for you ?

**Comment by Grenadingue** [comment]
Yes, it looks fine for me

**Comment by lumy** [comment]
So should we keep the solution of writting the logbook every  X turn, or now that we removed the populations from it (and saved on another file) and the object is little in memory, should we just write it at the end ?

EDIT: I choosed to let the file be wrote at the end only because it simpler and without the population it's way faster.
